apiVersion: v1
kind: Pod
metadata:
  name: copy-file
spec:
  volumes:
    - name: shared-volume
      hostPath:
        path: "/home/docker/file.txt"
        type: FileOrCreate
  # initContainers:
  #   - name: one
  #     image: debian
  #     volumeMounts:
  #       - name: shared-volume
  #         mountPath: /home/file.txt 
  #         subPath: file.txt
      # command: [ "/bin/bash", "-ce", "echo hello > /home/file.txt" ]
  containers:
    - name: two
      image: debian
      volumeMounts:
        - name: shared-volume
          mountPath: /home/file.txt 
      command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
